name: domicile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.0+3
  scrollable_positioned_list: ^0.3.8
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  firebase_auth: ^4.6.3
  cloud_firestore: any
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  circular_bottom_navigation: ^2.3.0
  provider: ^6.0.5
  json_annotation: ^4.8.1
  image_picker: ^0.8.9
  google_sign_in: ^6.1.4
  carousel_slider: ^4.2.1
  floating_action_bubble: ^1.1.4
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  path: ^1.8.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/logo.PNG
  image_dark: assets/images/logo.PNG

  android_12:
    image: assets/images/logo.PNG
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/logo.PNG
    icon_background_color_dark: "272727"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  #fonts:
  #  - family: sans_regular
  #    fonts:
  #      - asset: assets/fonts/sans_regular.ttf
